server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book/**
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/pet/**
        - id: clientMS
          uri: lb://clientMS
          predicates:
            - Path=/api/v1/clients/**
        - id: bookingVoucherMS
          uri: lb://bookingVoucherMS
          predicates:
            - Path=/api/v1/booking/**
        - id: feeMS
          uri: lb://feeMS
          predicates:
            - Path=/api/v1/fee/**
        - id: frecuencyClentsMS
          uri: lb://frecuencyClentsMS
          predicates:
            - Path=/api/v1/frecuency/**
        - id: especialDayMS
          uri: lb://especialDayMS
          predicates:
            - Path=/api/v1/especialDay/**
        - id: personNumberMS
          uri: lb://personNumberMS
          predicates:
            - Path=/api/v1/personNumber/**